/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by AstraForge — register offsets are placeholders */
#ifndef _HDA_INTEL_H_
#define _HDA_INTEL_H_

#include <linux/types.h>
#include <linux/pci.h>

#define DRIVER_NAME     "hda_intel"
#define DRIVER_DESC     "Intel HD Audio Controller"
#define DRIVER_VERSION  "1.0.0"

/* Device identifiers */
#define HDA_INTEL_VENDOR_ID  0x8086
#define HDA_INTEL_DEVICE_ID  0x7AD0

/* Register map — PLACEHOLDER (fill from reverse engineering) */
#define HDA_INTEL_REG_CTRL      0x0000
#define HDA_INTEL_REG_STATUS    0x0004
#define HDA_INTEL_REG_INT_MASK  0x0008
#define HDA_INTEL_REG_INT_STAT  0x000c
#define HDA_INTEL_REG_TX_BASE   0x0010
#define HDA_INTEL_REG_RX_BASE   0x0014


#endif /* _HDA_INTEL_H_ */
