/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by AstraForge — register offsets are placeholders */
#ifndef _IWL0033_H_
#define _IWL0033_H_

#include <linux/types.h>
#include <linux/pci.h>

#define DRIVER_NAME     "iwl0033"
#define DRIVER_DESC     "Intel Bluetooth"
#define DRIVER_VERSION  "22.0"

/* Device identifiers */
#define IWL0033_VENDOR_ID  0x8087
#define IWL0033_DEVICE_ID  0x0033

/* Register map — PLACEHOLDER (fill from reverse engineering) */
#define IWL0033_REG_CTRL      0x0000
#define IWL0033_REG_STATUS    0x0004
#define IWL0033_REG_INT_MASK  0x0008
#define IWL0033_REG_INT_STAT  0x000c
#define IWL0033_REG_TX_BASE   0x0010
#define IWL0033_REG_RX_BASE   0x0014


#endif /* _IWL0033_H_ */
