        // SPDX-License-Identifier: GPL-2.0
        /*
         * Intel Bluetooth — Linux Driver Skeleton
         * Type     : Bluetooth (HCI)
         * Provider : Intel
         * Version  : 22.0
         * PCI/USB  : 0x8087:0x0033  [USB]
         * Class    : Bluetooth
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>
        #include <linux/usb.h>
#include <net/bluetooth/bluetooth.h>
#include <net/bluetooth/hci_core.h>

        #include "iwl0033.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        static const struct usb_device_id iwl0033_usb_table[] = {
	{ USB_DEVICE(IWL0033_VENDOR_ID, IWL0033_DEVICE_ID) },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(usb, iwl0033_usb_table);

static int iwl0033_probe(struct usb_interface *intf,
			 const struct usb_device_id *id)
{
	struct hci_dev *hdev;
	int ret;
	hdev = hci_alloc_dev();
	if (!hdev) return -ENOMEM;
	hdev->bus     = HCI_USB;
	hdev->dev_type = HCI_PRIMARY;
	/* TODO: set hdev->open / close / flush / send */
	ret = hci_register_dev(hdev);
	if (ret) { hci_free_dev(hdev); return ret; }
	usb_set_intfdata(intf, hdev);
	return 0;
}

static void iwl0033_disconnect(struct usb_interface *intf)
{
	struct hci_dev *hdev = usb_get_intfdata(intf);
	if (hdev) { hci_unregister_dev(hdev); hci_free_dev(hdev); }
}

static struct usb_driver iwl0033_usb_driver = {
	.name       = DRIVER_NAME,
	.id_table   = iwl0033_usb_table,
	.probe      = iwl0033_probe,
	.disconnect = iwl0033_disconnect,
};
module_usb_driver(iwl0033_usb_driver);

