        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _RTL8125_H_
        #define _RTL8125_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "rtl8125"
        #define DRIVER_DESC     "Realtek PCIe GbE"
        #define DRIVER_VERSION  "10.0"

        /* Device identifiers */
        #define RTL8125_VENDOR_ID  0x10EC
        #define RTL8125_DEVICE_ID  0x8125

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define RTL8125_REG_CTRL      0x0000
        #define RTL8125_REG_STATUS    0x0004
        #define RTL8125_REG_INT_MASK  0x0008
        #define RTL8125_REG_INT_STAT  0x000c
        #define RTL8125_REG_TX_BASE   0x0010
        #define RTL8125_REG_RX_BASE   0x0014

        struct rtl8125_dev {
	struct pci_dev  *pdev;
	void __iomem    *base;
};

        #endif /* _RTL8125_H_ */
