        // SPDX-License-Identifier: GPL-2.0
        /*
         * Realtek PCIe GbE — Linux Driver Skeleton
         * Type     : Ethernet (net_device / PCI)
         * Provider : Realtek
         * Version  : 10.0
         * PCI/USB  : 0x10EC:0x8125  [PCI]
         * Class    : Net
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>
        #include <linux/netdevice.h>
#include <linux/etherdevice.h>

        #include "rtl8125.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        static const struct pci_device_id rtl8125_pci_table[] = {
	{ PCI_DEVICE(RTL8125_VENDOR_ID, RTL8125_DEVICE_ID) },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(pci, rtl8125_pci_table);

static int rtl8125_net_open(struct net_device *ndev)
{
	netif_start_queue(ndev);
	return 0; /* TODO: enable DMA, enable IRQ */
}

static int rtl8125_net_stop(struct net_device *ndev)
{
	netif_stop_queue(ndev);
	return 0; /* TODO: disable DMA, disable IRQ */
}

static netdev_tx_t rtl8125_start_xmit(struct sk_buff *skb,
				   struct net_device *ndev)
{
	/* TODO: enqueue skb to TX descriptor ring */
	dev_kfree_skb_any(skb);
	return NETDEV_TX_OK;
}

static void rtl8125_get_stats64(struct net_device *ndev,
				 struct rtnl_link_stats64 *stats)
{
	/* TODO: read hardware counters into stats */
}

static const struct net_device_ops rtl8125_netdev_ops = {
	.ndo_open        = rtl8125_net_open,
	.ndo_stop        = rtl8125_net_stop,
	.ndo_start_xmit  = rtl8125_start_xmit,
	.ndo_get_stats64 = rtl8125_get_stats64,
};

static int rtl8125_pci_probe(struct pci_dev *pdev,
			   const struct pci_device_id *id)
{
	struct net_device *ndev;
	struct rtl8125_dev   *priv;
	int ret;

	ret = pcim_enable_device(pdev);
	if (ret) return ret;
	ret = pcim_iomap_regions(pdev, BIT(0), DRIVER_NAME);
	if (ret) return ret;
	pci_set_master(pdev);
	ret = dma_set_mask_and_coherent(&pdev->dev, DMA_BIT_MASK(64));
	if (ret)
		ret = dma_set_mask_and_coherent(&pdev->dev, DMA_BIT_MASK(32));
	if (ret) return ret;

	ndev = devm_alloc_etherdev(&pdev->dev, sizeof(*priv));
	if (!ndev) return -ENOMEM;

	priv       = netdev_priv(ndev);
	priv->pdev = pdev;
	priv->base = pcim_iomap_table(pdev)[0];
	SET_NETDEV_DEV(ndev, &pdev->dev);
	ndev->netdev_ops = &rtl8125_netdev_ops;

	/* TODO: read MAC address from hardware */
	eth_hw_addr_random(ndev);

	ret = register_netdev(ndev);
	if (ret) return ret;

	pci_set_drvdata(pdev, ndev);
	dev_info(&pdev->dev, "%s up\n", DRIVER_DESC);
	return 0;
}

static void rtl8125_pci_remove(struct pci_dev *pdev)
{
	struct net_device *ndev = pci_get_drvdata(pdev);
	if (ndev) unregister_netdev(ndev);
}

static int  rtl8125_suspend(struct device *d) { return 0; }
static int  rtl8125_resume(struct device *d)  { return 0; }
static SIMPLE_DEV_PM_OPS(rtl8125_pm_ops, rtl8125_suspend, rtl8125_resume);

static struct pci_driver rtl8125_pci_driver = {
	.name      = DRIVER_NAME,
	.id_table  = rtl8125_pci_table,
	.probe     = rtl8125_pci_probe,
	.remove    = rtl8125_pci_remove,
	.driver.pm = &rtl8125_pm_ops,
};
module_pci_driver(rtl8125_pci_driver);

