        // SPDX-License-Identifier: GPL-2.0
        /*
         * Some Unknown PCI Device — Linux Driver Skeleton
         * Type     : Generic PCI
         * Provider : Test Vendor
         * Version  : 1.0.0
         * PCI/USB  : 0xABCD:0x1234  [PCI]
         * Class    : Unknown
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>


        #include "unknwn.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        static const struct pci_device_id unknwn_pci_table[] = {
	{ PCI_DEVICE(UNKNWN_VENDOR_ID, UNKNWN_DEVICE_ID) },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(pci, unknwn_pci_table);

static int unknwn_pci_probe(struct pci_dev *pdev,
			   const struct pci_device_id *id)
{
	struct unknwn_dev *dev;
	int ret;

	ret = pcim_enable_device(pdev);
	if (ret) return ret;
	ret = pcim_iomap_regions(pdev, BIT(0), DRIVER_NAME);
	if (ret) return ret;
	pci_set_master(pdev);

	dev = devm_kzalloc(&pdev->dev, sizeof(*dev), GFP_KERNEL);
	if (!dev) return -ENOMEM;
	dev->pdev = pdev;
	dev->base = pcim_iomap_table(pdev)[0];
	pci_set_drvdata(pdev, dev);

	/* TODO: device-specific initialisation */
	dev_info(&pdev->dev, "%s up\n", DRIVER_DESC);
	return 0;
}

static void unknwn_pci_remove(struct pci_dev *pdev)
{
	/* TODO: stop device */
}

static int  unknwn_suspend(struct device *d) { return 0; }
static int  unknwn_resume(struct device *d)  { return 0; }
static SIMPLE_DEV_PM_OPS(unknwn_pm_ops, unknwn_suspend, unknwn_resume);

static struct pci_driver unknwn_pci_driver = {
	.name      = DRIVER_NAME,
	.id_table  = unknwn_pci_table,
	.probe     = unknwn_pci_probe,
	.remove    = unknwn_pci_remove,
	.driver.pm = &unknwn_pm_ops,
};
module_pci_driver(unknwn_pci_driver);

