        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _UNKNWN_H_
        #define _UNKNWN_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "unknwn"
        #define DRIVER_DESC     "Some Unknown PCI Device"
        #define DRIVER_VERSION  "1.0.0"

        /* Device identifiers */
        #define UNKNWN_VENDOR_ID  0xABCD
        #define UNKNWN_DEVICE_ID  0x1234

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define UNKNWN_REG_CTRL      0x0000
        #define UNKNWN_REG_STATUS    0x0004
        #define UNKNWN_REG_INT_MASK  0x0008
        #define UNKNWN_REG_INT_STAT  0x000c
        #define UNKNWN_REG_TX_BASE   0x0010
        #define UNKNWN_REG_RX_BASE   0x0014

        struct unknwn_dev {
	struct pci_dev *pdev;
	void __iomem   *base;
};

        #endif /* _UNKNWN_H_ */
