        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _RTL8153_H_
        #define _RTL8153_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "rtl8153"
        #define DRIVER_DESC     "Realtek USB GbE Family Controller"
        #define DRIVER_VERSION  "1.0.0"

        /* Device identifiers */
        #define RTL8153_VENDOR_ID  0x0BDA
        #define RTL8153_DEVICE_ID  0x8153

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define RTL8153_REG_CTRL      0x0000
        #define RTL8153_REG_STATUS    0x0004
        #define RTL8153_REG_INT_MASK  0x0008
        #define RTL8153_REG_INT_STAT  0x000c
        #define RTL8153_REG_TX_BASE   0x0010
        #define RTL8153_REG_RX_BASE   0x0014

        struct rtl8153_dev {
	struct usb_device    *udev;
	struct usb_interface *intf;
};

        #endif /* _RTL8153_H_ */
