        // SPDX-License-Identifier: GPL-2.0
        /*
         * Realtek USB GbE Family Controller — Linux Driver Skeleton
         * Type     : USB (generic)
         * Provider : Test Vendor
         * Version  : 1.0.0
         * PCI/USB  : 0x0BDA:0x8153  [USB]
         * Class    : Net
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>
        #include <linux/usb.h>

        #include "rtl8153.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        static const struct usb_device_id rtl8153_usb_table[] = {
	{ USB_DEVICE(RTL8153_VENDOR_ID, RTL8153_DEVICE_ID) },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(usb, rtl8153_usb_table);

static int rtl8153_probe(struct usb_interface *intf,
			 const struct usb_device_id *id)
{
	struct usb_device *udev = interface_to_usbdev(intf);
	/* TODO: claim interface, allocate URBs, start I/O */
	dev_info(&intf->dev, "%s attached\n", DRIVER_DESC);
	return 0;
}

static void rtl8153_disconnect(struct usb_interface *intf)
{
	/* TODO: cancel URBs, free resources */
}

static int rtl8153_suspend(struct usb_interface *intf, pm_message_t msg)
{ return 0; }

static int rtl8153_resume(struct usb_interface *intf)
{ return 0; }

static struct usb_driver rtl8153_usb_driver = {
	.name       = DRIVER_NAME,
	.id_table   = rtl8153_usb_table,
	.probe      = rtl8153_probe,
	.disconnect = rtl8153_disconnect,
	.suspend    = rtl8153_suspend,
	.resume     = rtl8153_resume,
};
module_usb_driver(rtl8153_usb_driver);

