        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _MY_WIFI_DRIVER_H_
        #define _MY_WIFI_DRIVER_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "my_wifi_driver"
        #define DRIVER_DESC     "TP-Link Wi-Fi 7 PCIe Adapter"
        #define DRIVER_VERSION  "5.3.0.1781"

        /* Device identifiers */
        #define MY_WIFI_DRIVER_VENDOR_ID  0x14C3
        #define MY_WIFI_DRIVER_DEVICE_ID  0x7927
        #define MY_WIFI_DRIVER_SUBSYS_VENDOR  0xE104
#define MY_WIFI_DRIVER_SUBSYS_DEVICE  0x105B

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define MY_WIFI_DRIVER_REG_CTRL      0x0000
        #define MY_WIFI_DRIVER_REG_STATUS    0x0004
        #define MY_WIFI_DRIVER_REG_INT_MASK  0x0008
        #define MY_WIFI_DRIVER_REG_INT_STAT  0x000c
        #define MY_WIFI_DRIVER_REG_TX_BASE   0x0010
        #define MY_WIFI_DRIVER_REG_RX_BASE   0x0014

        struct my_wifi_driver_dev {
	struct pci_dev      *pdev;
	struct ieee80211_hw *hw;
	void __iomem        *base;
};

        #endif /* _MY_WIFI_DRIVER_H_ */
