/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by AstraForge — register offsets are placeholders */
#ifndef _V046DDC07C_H_
#define _V046DDC07C_H_

#include <linux/types.h>
#include <linux/pci.h>

#define DRIVER_NAME     "v046ddc07c"
#define DRIVER_DESC     "Logitech G502"
#define DRIVER_VERSION  "1.0"

/* Device identifiers */
#define V046DDC07C_VENDOR_ID  0x046D
#define V046DDC07C_DEVICE_ID  0xC07C

/* Register map — PLACEHOLDER (fill from reverse engineering) */
#define V046DDC07C_REG_CTRL      0x0000
#define V046DDC07C_REG_STATUS    0x0004
#define V046DDC07C_REG_INT_MASK  0x0008
#define V046DDC07C_REG_INT_STAT  0x000c
#define V046DDC07C_REG_TX_BASE   0x0010
#define V046DDC07C_REG_RX_BASE   0x0014


#endif /* _V046DDC07C_H_ */
