        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — do not rely on register offsets until verified */
        #ifndef _MT7927_H_
        #define _MT7927_H_

        #include <linux/pci.h>
        #include <linux/types.h>
        #include <net/mac80211.h>

        #define DRIVER_NAME     "mt7927"
        #define DRIVER_DESC     "TP-Link Wi-Fi 7 PCIe Adapter"
        #define DRIVER_VERSION  "5.3.0.1781"

        /* PCI identifiers */
        #define MT7927_VENDOR_ID   0x14C3
        #define MT7927_DEVICE_ID   0x7927
        #define MT7927_SUBSYS_VENDOR  0xE104
#define MT7927_SUBSYS_DEVICE  0x105B

        /* ============================================================
         * Register map — PLACEHOLDER
         * Fill in from Windows driver binary analysis / hardware docs
         * ============================================================ */
        #define MT7927_REG_CTRL      0x0000  /* TODO */
        #define MT7927_REG_STATUS    0x0004  /* TODO */
        #define MT7927_REG_INT_MASK  0x0008  /* TODO */
        #define MT7927_REG_INT_STAT  0x000c  /* TODO */
        #define MT7927_REG_TX_BASE   0x0010  /* TODO */
        #define MT7927_REG_RX_BASE   0x0014  /* TODO */

        /* ============================================================
         * Private device context
         * ============================================================ */
        struct mt7927_dev {
        	struct pci_dev       *pdev;
        	struct ieee80211_hw  *hw;
        	void __iomem         *base;

        	/* TODO: TX/RX ring descriptors */
        	/* TODO: firmware state */
        	/* TODO: interrupt counters */
        };

        static inline u32 mt7927_read32(struct mt7927_dev *dev, u32 reg)
        {
        	return readl(dev->base + reg);
        }

        static inline void mt7927_write32(struct mt7927_dev *dev, u32 reg, u32 val)
        {
        	writel(val, dev->base + reg);
        }

        #endif /* _MT7927_H_ */
