        // SPDX-License-Identifier: GPL-2.0
        /*
         * TP-Link Wi-Fi 7 PCIe Adapter — Linux Driver Skeleton
         *
         * Generated by AstraForge from Windows driver
         *   Provider : MediaTek, Inc.
         *   Version  : 5.3.0.1781
         *   PCI      : 0x14C3:0x7927
         *   Bands    : 2.4ghz, 5ghz, 6ghz
         *   Modes    : 802.11a, 802.11ac, 802.11ax, 802.11b, 802.11be, 802.11g, 802.11n
         *
         * Status: SKELETON — hardware register access not yet implemented.
         * Next steps:
         *   1. Reverse-engineer register map from Windows .sys binary
         *   2. Implement mt7927_start() / mt7927_tx() / mt7927_config()
         *   3. Load firmware via request_firmware()
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/netdevice.h>
        #include <linux/etherdevice.h>
        #include <linux/firmware.h>
        #include <linux/dma-mapping.h>
        #include <net/mac80211.h>

        #include "mt7927.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        /* No firmware files identified from Windows driver */

        /* ============================================================
         * PCI device table
         * ============================================================ */

        static const struct pci_device_id mt7927_pci_table[] = {
        	{ PCI_DEVICE(MT7927_VENDOR_ID, MT7927_DEVICE_ID) },
        	{ PCI_DEVICE_SUB(MT7927_VENDOR_ID, MT7927_DEVICE_ID, 0xE104, 0x105B) },
	{ /* sentinel */ }
        };
        MODULE_DEVICE_TABLE(pci, mt7927_pci_table);

        /* ============================================================
         * IEEE 802.11 channel / rate / band tables
         * ============================================================ */

        #define CHAN2G(_freq, _idx) {                     \
    .band        = NL80211_BAND_2GHZ,           \
    .center_freq = (_freq),                     \
    .hw_value    = (_idx),                      \
    .max_power   = 20,                          \
}

static struct ieee80211_channel mt7927_2ghz_channels[] = {
    CHAN2G(2412,  1), CHAN2G(2417,  2), CHAN2G(2422,  3),
    CHAN2G(2427,  4), CHAN2G(2432,  5), CHAN2G(2437,  6),
    CHAN2G(2442,  7), CHAN2G(2447,  8), CHAN2G(2452,  9),
    CHAN2G(2457, 10), CHAN2G(2462, 11), CHAN2G(2467, 12),
    CHAN2G(2472, 13),
};

static struct ieee80211_rate mt7927_2ghz_rates[] = {
    { .bitrate = 10,  .hw_value = 0x00 },
    { .bitrate = 20,  .hw_value = 0x01, .flags = IEEE80211_RATE_SHORT_PREAMBLE },
    { .bitrate = 55,  .hw_value = 0x02, .flags = IEEE80211_RATE_SHORT_PREAMBLE },
    { .bitrate = 110, .hw_value = 0x03, .flags = IEEE80211_RATE_SHORT_PREAMBLE },
    { .bitrate = 60,  .hw_value = 0x04 },
    { .bitrate = 90,  .hw_value = 0x05 },
    { .bitrate = 120, .hw_value = 0x06 },
    { .bitrate = 180, .hw_value = 0x07 },
    { .bitrate = 240, .hw_value = 0x08 },
    { .bitrate = 360, .hw_value = 0x09 },
    { .bitrate = 480, .hw_value = 0x0a },
    { .bitrate = 540, .hw_value = 0x0b },
};

static struct ieee80211_supported_band mt7927_band_2ghz = {
    .channels   = mt7927_2ghz_channels,
    .n_channels = ARRAY_SIZE(mt7927_2ghz_channels),
    .rates      = mt7927_2ghz_rates,
    .n_rates    = ARRAY_SIZE(mt7927_2ghz_rates),
    .ht_cap = {
        .ht_supported = true,
        .cap = IEEE80211_HT_CAP_SGI_20 | IEEE80211_HT_CAP_SGI_40
             | IEEE80211_HT_CAP_SUP_WIDTH_20_40
             | IEEE80211_HT_CAP_DSSSCCK40,
        .ampdu_factor  = IEEE80211_HT_MAX_AMPDU_64K,
        .ampdu_density = IEEE80211_HT_MPDU_DENSITY_8,
        .mcs = {
            .rx_mask = { 0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0 },
            .tx_params = IEEE80211_HT_MCS_TX_DEFINED,
        },
    },
};

#define CHAN5G(_freq, _idx) {                     \
    .band        = NL80211_BAND_5GHZ,           \
    .center_freq = (_freq),                     \
    .hw_value    = (_idx),                      \
    .max_power   = 23,                          \
}

static struct ieee80211_channel mt7927_5ghz_channels[] = {
    /* UNII-1 */
    CHAN5G(5180, 36),  CHAN5G(5200, 40),  CHAN5G(5220, 44),  CHAN5G(5240, 48),
    /* UNII-2A */
    CHAN5G(5260, 52),  CHAN5G(5280, 56),  CHAN5G(5300, 60),  CHAN5G(5320, 64),
    /* UNII-2C */
    CHAN5G(5500, 100), CHAN5G(5520, 104), CHAN5G(5540, 108), CHAN5G(5560, 112),
    CHAN5G(5580, 116), CHAN5G(5600, 120), CHAN5G(5620, 124), CHAN5G(5640, 128),
    CHAN5G(5660, 132), CHAN5G(5680, 136), CHAN5G(5700, 140), CHAN5G(5720, 144),
    /* UNII-3 */
    CHAN5G(5745, 149), CHAN5G(5765, 153), CHAN5G(5785, 157),
    CHAN5G(5805, 161), CHAN5G(5825, 165),
};

static struct ieee80211_rate mt7927_5ghz_rates[] = {
    { .bitrate = 60,  .hw_value = 0x00 },
    { .bitrate = 90,  .hw_value = 0x01 },
    { .bitrate = 120, .hw_value = 0x02 },
    { .bitrate = 180, .hw_value = 0x03 },
    { .bitrate = 240, .hw_value = 0x04 },
    { .bitrate = 360, .hw_value = 0x05 },
    { .bitrate = 480, .hw_value = 0x06 },
    { .bitrate = 540, .hw_value = 0x07 },
};

static struct ieee80211_supported_band mt7927_band_5ghz = {
    .channels   = mt7927_5ghz_channels,
    .n_channels = ARRAY_SIZE(mt7927_5ghz_channels),
    .rates      = mt7927_5ghz_rates,
    .n_rates    = ARRAY_SIZE(mt7927_5ghz_rates),
    .ht_cap = {
        .ht_supported = true,
        .cap = IEEE80211_HT_CAP_SGI_20 | IEEE80211_HT_CAP_SGI_40
             | IEEE80211_HT_CAP_SUP_WIDTH_20_40,
        .ampdu_factor  = IEEE80211_HT_MAX_AMPDU_64K,
        .ampdu_density = IEEE80211_HT_MPDU_DENSITY_8,
        .mcs = {
            .rx_mask = { 0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0 },
            .tx_params = IEEE80211_HT_MCS_TX_DEFINED,
        },
    },
    .vht_cap = {
        .vht_supported = true,
        .cap = IEEE80211_VHT_CAP_MAX_MPDU_LENGTH_11454
             | IEEE80211_VHT_CAP_RXLDPC
             | IEEE80211_VHT_CAP_SHORT_GI_80
             | IEEE80211_VHT_CAP_TXSTBC
             | IEEE80211_VHT_CAP_RXSTBC_1
             | IEEE80211_VHT_CAP_MAX_A_MPDU_LENGTH_EXPONENT_MASK,
        .vht_mcs = {
            .rx_mcs_map = cpu_to_le16(0xfffa),
            .tx_mcs_map = cpu_to_le16(0xfffa),
        },
    },
};

#define CHAN6G(_freq, _idx) {                     \
    .band        = NL80211_BAND_6GHZ,           \
    .center_freq = (_freq),                     \
    .hw_value    = (_idx),                      \
    .max_power   = 23,                          \
}

static struct ieee80211_channel mt7927_6ghz_channels[] = {
    CHAN6G(5955,   1), CHAN6G(5975,   5), CHAN6G(5995,   9), CHAN6G(6015,  13),
    CHAN6G(6035,  17), CHAN6G(6055,  21), CHAN6G(6075,  25), CHAN6G(6095,  29),
    CHAN6G(6115,  33), CHAN6G(6135,  37), CHAN6G(6155,  41), CHAN6G(6175,  45),
    CHAN6G(6195,  49), CHAN6G(6215,  53), CHAN6G(6235,  57), CHAN6G(6255,  61),
    CHAN6G(6275,  65), CHAN6G(6295,  69), CHAN6G(6315,  73), CHAN6G(6335,  77),
    CHAN6G(6355,  81), CHAN6G(6375,  85), CHAN6G(6395,  89), CHAN6G(6415,  93),
    CHAN6G(6435,  97), CHAN6G(6455, 101), CHAN6G(6475, 105), CHAN6G(6495, 109),
    CHAN6G(6515, 113), CHAN6G(6535, 117), CHAN6G(6555, 121), CHAN6G(6575, 125),
    CHAN6G(6595, 129), CHAN6G(6615, 133), CHAN6G(6635, 137), CHAN6G(6655, 141),
    CHAN6G(6675, 145), CHAN6G(6695, 149), CHAN6G(6715, 153), CHAN6G(6735, 157),
    CHAN6G(6755, 161), CHAN6G(6775, 165), CHAN6G(6795, 169), CHAN6G(6815, 173),
    CHAN6G(6835, 177), CHAN6G(6855, 181), CHAN6G(6875, 185), CHAN6G(6895, 189),
    CHAN6G(6915, 193), CHAN6G(6935, 197), CHAN6G(6955, 201), CHAN6G(6975, 205),
    CHAN6G(6995, 209), CHAN6G(7015, 213), CHAN6G(7035, 217), CHAN6G(7055, 221),
    CHAN6G(7075, 225), CHAN6G(7095, 229), CHAN6G(7115, 233),
};

static struct ieee80211_supported_band mt7927_band_6ghz = {
    .channels   = mt7927_6ghz_channels,
    .n_channels = ARRAY_SIZE(mt7927_6ghz_channels),
    .rates      = NULL,
    .n_rates    = 0,
};


        /* ============================================================
         * mac80211 ops  (implement these to make the driver functional)
         * ============================================================ */

        static void mt7927_tx(struct ieee80211_hw *hw,
        			  struct ieee80211_tx_control *control,
        			  struct sk_buff *skb)
        {
        	/* TODO: queue skb to hardware TX ring */
        	dev_kfree_skb_any(skb);
        }

        static int mt7927_start(struct ieee80211_hw *hw)
        {
        	/* TODO: enable IRQ, load firmware, start DMA */
        	return 0;
        }

        static void mt7927_stop(struct ieee80211_hw *hw, bool suspend)
        {
        	/* TODO: disable IRQ, stop DMA */
        }

        static int mt7927_add_interface(struct ieee80211_hw *hw,
        				    struct ieee80211_vif *vif)
        {
        	return 0;
        }

        static void mt7927_remove_interface(struct ieee80211_hw *hw,
        				       struct ieee80211_vif *vif)
        {
        }

        static int mt7927_config(struct ieee80211_hw *hw, u32 changed)
        {
        	/* TODO: apply channel/power changes to hardware */
        	return 0;
        }

        static void mt7927_configure_filter(struct ieee80211_hw *hw,
        				       unsigned int changed_flags,
        				       unsigned int *total_flags,
        				       u64 multicast)
        {
        	*total_flags &= FIF_ALLMULTI;
        }

        static int mt7927_set_key(struct ieee80211_hw *hw,
        			    enum set_key_cmd cmd,
        			    struct ieee80211_vif *vif,
        			    struct ieee80211_sta *sta,
        			    struct ieee80211_key_conf *key)
        {
        	/* TODO: program key into hardware crypto engine */
        	return -EOPNOTSUPP;
        }

        static const struct ieee80211_ops mt7927_ops = {
        	.tx               = mt7927_tx,
        	.start            = mt7927_start,
        	.stop             = mt7927_stop,
        	.add_interface    = mt7927_add_interface,
        	.remove_interface = mt7927_remove_interface,
        	.config           = mt7927_config,
        	.configure_filter = mt7927_configure_filter,
        	.set_key          = mt7927_set_key,
        };

        /* ============================================================
         * PCI driver callbacks
         * ============================================================ */

        static int mt7927_pci_probe(struct pci_dev *pdev,
        				 const struct pci_device_id *id)
        {
        	struct ieee80211_hw *hw;
        	struct mt7927_dev *dev;
        	int ret;

        	ret = pcim_enable_device(pdev);
        	if (ret) {
        		dev_err(&pdev->dev, "pcim_enable_device: %d\n", ret);
        		return ret;
        	}

        	ret = pcim_iomap_regions(pdev, BIT(0), DRIVER_NAME);
        	if (ret) {
        		dev_err(&pdev->dev, "pcim_iomap_regions: %d\n", ret);
        		return ret;
        	}

        	pci_set_master(pdev);

        	ret = dma_set_mask_and_coherent(&pdev->dev, DMA_BIT_MASK(32));
        	if (ret) {
        		dev_err(&pdev->dev, "dma_set_mask: %d\n", ret);
        		return ret;
        	}

        	hw = ieee80211_alloc_hw(sizeof(*dev), &mt7927_ops);
        	if (!hw)
        		return -ENOMEM;

        	dev       = hw->priv;
        	dev->pdev = pdev;
        	dev->hw   = hw;
        	dev->base = pcim_iomap_table(pdev)[0];

        	SET_IEEE80211_DEV(hw, &pdev->dev);

        	hw->wiphy->interface_modes =
        		BIT(NL80211_IFTYPE_STATION) |
        		BIT(NL80211_IFTYPE_AP)      |
        		BIT(NL80211_IFTYPE_MONITOR);

        	hw->queues          = 4;
        	hw->max_rates       = 4;
        	hw->max_rate_tries  = 11;
        	hw->extra_tx_headroom = 0;

        	hw->wiphy->bands[NL80211_BAND_2GHZ] = &mt7927_band_2ghz;
	hw->wiphy->bands[NL80211_BAND_5GHZ] = &mt7927_band_5ghz;
	hw->wiphy->bands[NL80211_BAND_6GHZ] = &mt7927_band_6ghz;

        	ret = ieee80211_register_hw(hw);
        	if (ret) {
        		dev_err(&pdev->dev, "ieee80211_register_hw: %d\n", ret);
        		ieee80211_free_hw(hw);
        		return ret;
        	}

        	pci_set_drvdata(pdev, hw);
        	dev_info(&pdev->dev, "%s up\n", DRIVER_DESC);
        	return 0;
        }

        static void mt7927_pci_remove(struct pci_dev *pdev)
        {
        	struct ieee80211_hw *hw = pci_get_drvdata(pdev);

        	if (!hw)
        		return;
        	ieee80211_unregister_hw(hw);
        	ieee80211_free_hw(hw);
        }

        static int mt7927_pci_suspend(struct device *dev_)
        {
        	/* TODO: save state, power down */
        	return 0;
        }

        static int mt7927_pci_resume(struct device *dev_)
        {
        	/* TODO: restore state, power up */
        	return 0;
        }

        static SIMPLE_DEV_PM_OPS(mt7927_pm_ops,
        			    mt7927_pci_suspend,
        			    mt7927_pci_resume);

        static struct pci_driver mt7927_pci_driver = {
        	.name      = DRIVER_NAME,
        	.id_table  = mt7927_pci_table,
        	.probe     = mt7927_pci_probe,
        	.remove    = mt7927_pci_remove,
        	.driver.pm = &mt7927_pm_ops,
        };

        module_pci_driver(mt7927_pci_driver);
