        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _NVME_SAM_H_
        #define _NVME_SAM_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "nvme_sam"
        #define DRIVER_DESC     "Samsung NVMe SSD 980 Pro"
        #define DRIVER_VERSION  "1.0.0"

        /* Device identifiers */
        #define NVME_SAM_VENDOR_ID  0x144D
        #define NVME_SAM_DEVICE_ID  0xA80A

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define NVME_SAM_REG_CTRL      0x0000
        #define NVME_SAM_REG_STATUS    0x0004
        #define NVME_SAM_REG_INT_MASK  0x0008
        #define NVME_SAM_REG_INT_STAT  0x000c
        #define NVME_SAM_REG_TX_BASE   0x0010
        #define NVME_SAM_REG_RX_BASE   0x0014

        struct nvme_sam_dev {
	struct pci_dev *pdev;
	void __iomem   *base;
};

        #endif /* _NVME_SAM_H_ */
