        // SPDX-License-Identifier: GPL-2.0
        /*
         * Samsung NVMe SSD 980 Pro — Linux Driver Skeleton
         * Type     : Storage (SCSI/NVMe)
         * Provider : Test Vendor
         * Version  : 1.0.0
         * PCI/USB  : 0x144D:0xA80A  [PCI]
         * Class    : SCSIAdapter
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>


        #include "nvme_sam.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

        static const struct pci_device_id nvme_sam_pci_table[] = {
	{ PCI_DEVICE(NVME_SAM_VENDOR_ID, NVME_SAM_DEVICE_ID) },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(pci, nvme_sam_pci_table);

static int nvme_sam_pci_probe(struct pci_dev *pdev,
			   const struct pci_device_id *id)
{
	struct nvme_sam_dev *dev;
	int ret;

	ret = pcim_enable_device(pdev);
	if (ret) return ret;
	ret = pcim_iomap_regions(pdev, BIT(0), DRIVER_NAME);
	if (ret) return ret;
	pci_set_master(pdev);

	dev = devm_kzalloc(&pdev->dev, sizeof(*dev), GFP_KERNEL);
	if (!dev) return -ENOMEM;
	dev->pdev = pdev;
	dev->base = pcim_iomap_table(pdev)[0];
	pci_set_drvdata(pdev, dev);

	/* TODO: device-specific initialisation */
	dev_info(&pdev->dev, "%s up\n", DRIVER_DESC);
	return 0;
}

static void nvme_sam_pci_remove(struct pci_dev *pdev)
{
	/* TODO: stop device */
}

static int  nvme_sam_suspend(struct device *d) { return 0; }
static int  nvme_sam_resume(struct device *d)  { return 0; }
static SIMPLE_DEV_PM_OPS(nvme_sam_pm_ops, nvme_sam_suspend, nvme_sam_resume);

static struct pci_driver nvme_sam_pci_driver = {
	.name      = DRIVER_NAME,
	.id_table  = nvme_sam_pci_table,
	.probe     = nvme_sam_pci_probe,
	.remove    = nvme_sam_pci_remove,
	.driver.pm = &nvme_sam_pm_ops,
};
module_pci_driver(nvme_sam_pci_driver);

