/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by AstraForge — register offsets are placeholders */
#ifndef _G502_H_
#define _G502_H_

#include <linux/types.h>
#include <linux/pci.h>

#define DRIVER_NAME     "g502"
#define DRIVER_DESC     "Logitech G502 Gaming Mouse"
#define DRIVER_VERSION  "1.0.0"

/* Device identifiers */
#define G502_VENDOR_ID  0x046D
#define G502_DEVICE_ID  0xC07C

/* Register map — PLACEHOLDER (fill from reverse engineering) */
#define G502_REG_CTRL      0x0000
#define G502_REG_STATUS    0x0004
#define G502_REG_INT_MASK  0x0008
#define G502_REG_INT_STAT  0x000c
#define G502_REG_TX_BASE   0x0010
#define G502_REG_RX_BASE   0x0014


#endif /* _G502_H_ */
