        // SPDX-License-Identifier: GPL-2.0
        /*
         * Intel Wireless Bluetooth — Linux Driver Skeleton
         * Type     : WiFi (mac80211 / PCI)
         * Provider : Test Vendor
         * Version  : 1.0.0
         * PCI/USB  : 0x8087:0x0033  [USB]
         * Class    : Bluetooth
         * Bands    : n/a
         * Modes    : n/a
         *
         * Generated by AstraForge.
         * Hardware register access is NOT implemented — fill in the TODO stubs
         * after reverse-engineering the Windows .sys binary or obtaining datasheets.
         */

        #include <linux/module.h>
        #include <linux/pci.h>
        #include <linux/dma-mapping.h>
        #include <linux/firmware.h>
#include <net/mac80211.h>

        #include "btintel.h"

        MODULE_LICENSE("GPL");
        MODULE_AUTHOR("AstraForge <generated>");
        MODULE_DESCRIPTION(DRIVER_DESC);
        MODULE_VERSION(DRIVER_VERSION);

                /* No firmware files identified */

        static const struct pci_device_id btintel_pci_table[] = {
        	{ PCI_DEVICE(BTINTEL_VENDOR_ID, BTINTEL_DEVICE_ID) },
        	{ /* sentinel */ }
        };
        MODULE_DEVICE_TABLE(pci, btintel_pci_table);

        /* Band / channel / rate tables */
        #define CHAN2G(_f,_i) { .band=NL80211_BAND_2GHZ, .center_freq=(_f), .hw_value=(_i), .max_power=20 }
static struct ieee80211_channel btintel_2ghz_ch[] = {
    CHAN2G(2412,1),CHAN2G(2417,2),CHAN2G(2422,3),CHAN2G(2427,4),CHAN2G(2432,5),
    CHAN2G(2437,6),CHAN2G(2442,7),CHAN2G(2447,8),CHAN2G(2452,9),CHAN2G(2457,10),
    CHAN2G(2462,11),CHAN2G(2467,12),CHAN2G(2472,13),
};
static struct ieee80211_rate btintel_2ghz_rates[] = {
    {.bitrate=10,.hw_value=0}, {.bitrate=20,.hw_value=1,.flags=IEEE80211_RATE_SHORT_PREAMBLE},
    {.bitrate=55,.hw_value=2,.flags=IEEE80211_RATE_SHORT_PREAMBLE},
    {.bitrate=110,.hw_value=3,.flags=IEEE80211_RATE_SHORT_PREAMBLE},
    {.bitrate=60,.hw_value=4},  {.bitrate=90,.hw_value=5},
    {.bitrate=120,.hw_value=6}, {.bitrate=180,.hw_value=7},
    {.bitrate=240,.hw_value=8}, {.bitrate=360,.hw_value=9},
    {.bitrate=480,.hw_value=10},{.bitrate=540,.hw_value=11},
};
static struct ieee80211_supported_band btintel_band_2ghz = {
    .channels==btintel_2ghz_ch, .n_channels=ARRAY_SIZE(btintel_2ghz_ch),
    .rates=btintel_2ghz_rates,  .n_rates=ARRAY_SIZE(btintel_2ghz_rates),
    .ht_cap={.ht_supported=true,
        .cap=IEEE80211_HT_CAP_SGI_20|IEEE80211_HT_CAP_SGI_40|IEEE80211_HT_CAP_SUP_WIDTH_20_40,
        .ampdu_factor=IEEE80211_HT_MAX_AMPDU_64K,
        .ampdu_density=IEEE80211_HT_MPDU_DENSITY_8,
        .mcs={.rx_mask={0xff,0xff}, .tx_params=IEEE80211_HT_MCS_TX_DEFINED},
    },
};

#define CHAN5G(_f,_i) { .band=NL80211_BAND_5GHZ, .center_freq=(_f), .hw_value=(_i), .max_power=23 }
static struct ieee80211_channel btintel_5ghz_ch[] = {
    CHAN5G(5180,36), CHAN5G(5200,40), CHAN5G(5220,44), CHAN5G(5240,48),
    CHAN5G(5260,52), CHAN5G(5280,56), CHAN5G(5300,60), CHAN5G(5320,64),
    CHAN5G(5500,100),CHAN5G(5520,104),CHAN5G(5540,108),CHAN5G(5560,112),
    CHAN5G(5580,116),CHAN5G(5600,120),CHAN5G(5620,124),CHAN5G(5640,128),
    CHAN5G(5660,132),CHAN5G(5680,136),CHAN5G(5700,140),CHAN5G(5720,144),
    CHAN5G(5745,149),CHAN5G(5765,153),CHAN5G(5785,157),CHAN5G(5805,161),CHAN5G(5825,165),
};
static struct ieee80211_rate btintel_5ghz_rates[] = {
    {.bitrate=60,.hw_value=0}, {.bitrate=90,.hw_value=1},
    {.bitrate=120,.hw_value=2},{.bitrate=180,.hw_value=3},
    {.bitrate=240,.hw_value=4},{.bitrate=360,.hw_value=5},
    {.bitrate=480,.hw_value=6},{.bitrate=540,.hw_value=7},
};
static struct ieee80211_supported_band btintel_band_5ghz = {
    .channels=btintel_5ghz_ch, .n_channels=ARRAY_SIZE(btintel_5ghz_ch),
    .rates=btintel_5ghz_rates, .n_rates=ARRAY_SIZE(btintel_5ghz_rates),
    .ht_cap={.ht_supported=true,
        .cap=IEEE80211_HT_CAP_SGI_20|IEEE80211_HT_CAP_SGI_40|IEEE80211_HT_CAP_SUP_WIDTH_20_40,
        .ampdu_factor=IEEE80211_HT_MAX_AMPDU_64K, .ampdu_density=IEEE80211_HT_MPDU_DENSITY_8,
        .mcs={.rx_mask={0xff,0xff}, .tx_params=IEEE80211_HT_MCS_TX_DEFINED},
    },
    .vht_cap={.vht_supported=true,
        .cap=IEEE80211_VHT_CAP_MAX_MPDU_LENGTH_11454|IEEE80211_VHT_CAP_RXLDPC|
             IEEE80211_VHT_CAP_SHORT_GI_80|IEEE80211_VHT_CAP_TXSTBC|
             IEEE80211_VHT_CAP_RXSTBC_1|IEEE80211_VHT_CAP_MAX_A_MPDU_LENGTH_EXPONENT_MASK,
        .vht_mcs={.rx_mcs_map=cpu_to_le16(0xfffa), .tx_mcs_map=cpu_to_le16(0xfffa)},
    },
};


        /* mac80211 ops */
        static void btintel_tx(struct ieee80211_hw *hw,
        		    struct ieee80211_tx_control *control,
        		    struct sk_buff *skb)
        { dev_kfree_skb_any(skb); /* TODO: enqueue to TX ring */ }

        static int btintel_start(struct ieee80211_hw *hw)
        { return 0; /* TODO: enable IRQ, load firmware, start DMA */ }

        static void btintel_stop(struct ieee80211_hw *hw, bool suspend)
        { /* TODO: disable IRQ, stop DMA */ }

        static int btintel_add_interface(struct ieee80211_hw *hw,
        			       struct ieee80211_vif *vif)
        { return 0; }

        static void btintel_remove_interface(struct ieee80211_hw *hw,
        				  struct ieee80211_vif *vif) {}

        static int btintel_config(struct ieee80211_hw *hw, u32 changed)
        { return 0; /* TODO: apply channel/power to hardware */ }

        static void btintel_configure_filter(struct ieee80211_hw *hw,
        				  unsigned int changed_flags,
        				  unsigned int *total_flags, u64 multicast)
        { *total_flags &= FIF_ALLMULTI; }

        static int btintel_set_key(struct ieee80211_hw *hw, enum set_key_cmd cmd,
        			 struct ieee80211_vif *vif, struct ieee80211_sta *sta,
        			 struct ieee80211_key_conf *key)
        { return -EOPNOTSUPP; /* TODO: hardware crypto */ }

        static const struct ieee80211_ops btintel_ops = {
        	.tx               = btintel_tx,
        	.start            = btintel_start,
        	.stop             = btintel_stop,
        	.add_interface    = btintel_add_interface,
        	.remove_interface = btintel_remove_interface,
        	.config           = btintel_config,
        	.configure_filter = btintel_configure_filter,
        	.set_key          = btintel_set_key,
        };

        static int btintel_pci_probe(struct pci_dev *pdev,
        			   const struct pci_device_id *id)
        {
        	struct ieee80211_hw *hw;
        	struct btintel_dev *dev;
        	int ret;

        	ret = pcim_enable_device(pdev);
        	if (ret) return ret;
        	ret = pcim_iomap_regions(pdev, BIT(0), DRIVER_NAME);
        	if (ret) return ret;
        	pci_set_master(pdev);
        	ret = dma_set_mask_and_coherent(&pdev->dev, DMA_BIT_MASK(32));
        	if (ret) return ret;

        	hw = ieee80211_alloc_hw(sizeof(*dev), &btintel_ops);
        	if (!hw) return -ENOMEM;

        	dev = hw->priv;
        	dev->pdev = pdev;
        	dev->hw   = hw;
        	dev->base = pcim_iomap_table(pdev)[0];
        	SET_IEEE80211_DEV(hw, &pdev->dev);

        	hw->wiphy->interface_modes =
        		BIT(NL80211_IFTYPE_STATION) | BIT(NL80211_IFTYPE_AP) |
        		BIT(NL80211_IFTYPE_MONITOR);
        	hw->queues = 4; hw->max_rates = 4; hw->max_rate_tries = 11;

        	hw->wiphy->bands[NL80211_BAND_2GHZ] = &btintel_band_2ghz;
	hw->wiphy->bands[NL80211_BAND_5GHZ] = &btintel_band_5ghz;

        	ret = ieee80211_register_hw(hw);
        	if (ret) { ieee80211_free_hw(hw); return ret; }
        	pci_set_drvdata(pdev, hw);
        	dev_info(&pdev->dev, "%s up\n", DRIVER_DESC);
        	return 0;
        }

        static void btintel_pci_remove(struct pci_dev *pdev)
        {
        	struct ieee80211_hw *hw = pci_get_drvdata(pdev);
        	if (hw) { ieee80211_unregister_hw(hw); ieee80211_free_hw(hw); }
        }

        static int  btintel_suspend(struct device *d) { return 0; }
        static int  btintel_resume(struct device *d)  { return 0; }
        static SIMPLE_DEV_PM_OPS(btintel_pm_ops, btintel_suspend, btintel_resume);

        static struct pci_driver btintel_pci_driver = {
        	.name      = DRIVER_NAME,
        	.id_table  = btintel_pci_table,
        	.probe     = btintel_pci_probe,
        	.remove    = btintel_pci_remove,
        	.driver.pm = &btintel_pm_ops,
        };
        module_pci_driver(btintel_pci_driver);

