        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _BTINTEL_H_
        #define _BTINTEL_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "btintel"
        #define DRIVER_DESC     "Intel Wireless Bluetooth"
        #define DRIVER_VERSION  "1.0.0"

        /* Device identifiers */
        #define BTINTEL_VENDOR_ID  0x8087
        #define BTINTEL_DEVICE_ID  0x0033

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define BTINTEL_REG_CTRL      0x0000
        #define BTINTEL_REG_STATUS    0x0004
        #define BTINTEL_REG_INT_MASK  0x0008
        #define BTINTEL_REG_INT_STAT  0x000c
        #define BTINTEL_REG_TX_BASE   0x0010
        #define BTINTEL_REG_RX_BASE   0x0014

        struct btintel_dev {
	struct pci_dev      *pdev;
	struct ieee80211_hw *hw;
	void __iomem        *base;
};

        #endif /* _BTINTEL_H_ */
