        /* SPDX-License-Identifier: GPL-2.0 */
        /* Generated by AstraForge — register offsets are placeholders */
        #ifndef _MT7927_H_
        #define _MT7927_H_

        #include <linux/types.h>
        #include <linux/pci.h>

        #define DRIVER_NAME     "mt7927"
        #define DRIVER_DESC     "TP-Link Wi-Fi 7 PCIe Adapter"
        #define DRIVER_VERSION  "5.3.0.1781"

        /* Device identifiers */
        #define MT7927_VENDOR_ID  0x14C3
        #define MT7927_DEVICE_ID  0x7927
        #define MT7927_SUBSYS_VENDOR  0xE104
#define MT7927_SUBSYS_DEVICE  0x105B

        /* Register map — PLACEHOLDER (fill from reverse engineering) */
        #define MT7927_REG_CTRL      0x0000
        #define MT7927_REG_STATUS    0x0004
        #define MT7927_REG_INT_MASK  0x0008
        #define MT7927_REG_INT_STAT  0x000c
        #define MT7927_REG_TX_BASE   0x0010
        #define MT7927_REG_RX_BASE   0x0014

        struct mt7927_dev {
	struct pci_dev      *pdev;
	struct ieee80211_hw *hw;
	void __iomem        *base;
};

        #endif /* _MT7927_H_ */
